Resources:
  WebsiteVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: WebsiteVPC
  WebsitePublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebsiteVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: WebsitePublicSubnet
  WebsitePrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebsiteVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: WebsitePrivateSubnet
  WebsitePublicServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0100e595e1cc1ff7f
      InstanceType: t2.micro
      SubnetId: !Ref WebsitePublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      KeyName: Website-keypair
      Tags:
        - Key: Name
          Value: WebsitePublicServer
  WebsitePrivateServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0100e595e1cc1ff7f
      InstanceType: t2.micro
      SubnetId: !Ref WebsitePrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      KeyName: Website-keypair
      Tags:
        - Key: Name
          Value: WebsitePrivateServer
  #   Networking
  WebsiteIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: WebsiteIgw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref WebsiteVPC
      InternetGatewayId: !Ref WebsiteIgw
      Tags:
        - Key: Name
          Value: AttachGateway
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP inbound, all outbound
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PublicSecurityGroup
  PublicSecurityGroupIngressHTTP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicSecurityGroupIngressHTTP
  PublicSecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicSecurityGroupIngressSSH
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow  SSH inbound, all outbound
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PrivateSecurityGroup
  PrivateSecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PrivateSecurityGroup
      SourceSecurityGroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      Tags:
        - Key: Name
          Value: PrivateSecurityGroupIngressSSH
  # PublicRouteTable
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WebsiteIgw
      Tags:
        - Key: Name
          Value: PublicRoute
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref WebsitePublicSubnet
      Tags:
        - Key: Name
          Value: PublicSubnetRouteTableAssociation
  # PrivateRouteTable
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PrivateRouteTable
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref WebsitePrivateSubnet
      Tags:
        - Key: Name
          Value: PrivateSubnetRouteTableAssociation
  # Access Control List for public subnet
  PublicNAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PublicNAcl
  PublicSubnetNAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNAcl
      SubnetId: !Ref WebsitePublicSubnet
      Tags:
        - Key: Name
          Value: PublicSubnetNAclAssociation
  PublicNACLInboundAllTrafficRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicNACLInboundAllTrafficRule
  PublicNACLOutboundAllTrafficRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PublicNACLOutboundAllTrafficRule
  # Access Control List for Private subnet
  PrivateNAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref WebsiteVPC
      Tags:
        - Key: Name
          Value: PrivateNAcl
  PrivateSubnetNAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PrivateNAcl
      SubnetId: !Ref WebsitePrivateSubnet
      Tags:
        - Key: Name
          Value: PrivateSubnetNAclAssociation
  PrivateNACLInboundAllTrafficRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PrivateNACLInboundAllTrafficRule
  PrivateNACLOutboundAllTrafficRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PrivateNACLOutboundAllTrafficRule